import { Locale } from "@/hooks/useLocale";

export interface TermsSection {
  heading: string;
  body: string;
  items?: string[];
}

export interface TermsContent {
  title: string;
  updated: string;
  sections: TermsSection[];
}

export const TERMS: Record<Locale, TermsContent> = {
  en: {
    title: "Terms of Service",
    updated: "Last updated: April 27, 2026",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: 'By accessing or using BRITE Advisor ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.',
      },
      {
        heading: "2. Description of Service",
        body: "BRITE Advisor is an AI-powered architecture diagnostic tool based on the Business-Referenced Integration Technology Election (BRITE) framework. It provides recommendations and analysis based on user inputs and should be used as a decision-support tool, not as a substitute for professional architectural or technical advice.",
      },
      {
        heading: "3. User Accounts",
        body: "When you create an account, you are responsible for maintaining the confidentiality of your credentials and for all activity under your account. You agree to notify us immediately of any unauthorized use of your account.",
      },
      {
        heading: "4. Acceptable Use",
        body: "You agree not to:",
        items: [
          "Use the Service for any unlawful purpose or in violation of any regulations",
          "Attempt to gain unauthorized access to any part of the Service",
          "Reverse engineer, decompile, or disassemble any part of the Service",
          "Use automated means to access the Service without our express written permission",
          "Submit false or misleading information through the Service",
        ],
      },
      {
        heading: "5. Intellectual Property",
        body: "All content, branding, and technology within the Service are the exclusive property of BRITE Advisor and its licensors. The BRITE Framework name and methodology are protected intellectual property. Nothing in these Terms grants you any right to use our trademarks, logos, or other proprietary information.",
      },
      {
        heading: "6. AI-Generated Content",
        body: "Diagnoses and recommendations generated by our AI are provided for informational purposes only. We make no warranties regarding the accuracy, completeness, or fitness for a particular purpose of AI-generated content. You assume full responsibility for decisions made based on the Service's output.",
      },
      {
        heading: "7. Limitation of Liability",
        body: "To the maximum extent permitted by law, BRITE Advisor and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, even if advised of the possibility of such damages.",
      },
      {
        heading: "8. Modifications to Terms",
        body: "We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms. We will notify registered users of material changes via email.",
      },
      {
        heading: "9. Governing Law",
        body: "These Terms shall be governed by and construed in accordance with applicable law, without regard to conflict of law principles.",
      },
      {
        heading: "10. Contact",
        body: "Questions about these Terms? Contact us at legal@briteadvisor.com.",
      },
    ],
  },

  pt: {
    title: "Termos de Serviço",
    updated: "Última atualização: 27 de abril de 2026",
    sections: [
      {
        heading: "1. Aceitação dos Termos",
        body: 'Ao aceder ou utilizar o BRITE Advisor ("o Serviço"), concorda em ficar vinculado a estes Termos de Serviço. Se não concordar com estes termos, não utilize o Serviço.',
      },
      {
        heading: "2. Descrição do Serviço",
        body: "O BRITE Advisor é uma ferramenta de diagnóstico de arquitetura baseada em IA, fundamentada no framework Business-Referenced Integration Technology Election (BRITE). Fornece recomendações e análises com base nas entradas do utilizador e deve ser usado como ferramenta de apoio à decisão, não como substituto de aconselhamento profissional de arquitetura ou técnico.",
      },
      {
        heading: "3. Contas de Utilizador",
        body: "Ao criar uma conta, é responsável por manter a confidencialidade das suas credenciais e por toda a atividade realizada na sua conta. Concorda em notificar-nos imediatamente de qualquer uso não autorizado da sua conta.",
      },
      {
        heading: "4. Uso Aceitável",
        body: "Concorda em não:",
        items: [
          "Utilizar o Serviço para qualquer finalidade ilegal ou em violação de regulamentos",
          "Tentar obter acesso não autorizado a qualquer parte do Serviço",
          "Fazer engenharia reversa, descompilar ou desmontar qualquer parte do Serviço",
          "Usar meios automatizados para aceder ao Serviço sem nossa permissão expressa por escrito",
          "Submeter informações falsas ou enganosas através do Serviço",
        ],
      },
      {
        heading: "5. Propriedade Intelectual",
        body: "Todo o conteúdo, marca e tecnologia do Serviço são propriedade exclusiva do BRITE Advisor e dos seus licenciantes. O nome e a metodologia do BRITE Framework são propriedade intelectual protegida. Nada nestes Termos lhe concede qualquer direito de usar as nossas marcas registadas, logótipos ou outras informações proprietárias.",
      },
      {
        heading: "6. Conteúdo Gerado por IA",
        body: "Os diagnósticos e recomendações gerados pela nossa IA são fornecidos apenas para fins informativos. Não prestamos quaisquer garantias quanto à precisão, completude ou adequação para um fim específico do conteúdo gerado por IA. Assume total responsabilidade pelas decisões tomadas com base nos resultados do Serviço.",
      },
      {
        heading: "7. Limitação de Responsabilidade",
        body: "Na máxima extensão permitida por lei, o BRITE Advisor e os seus afiliados não serão responsáveis por quaisquer danos indiretos, incidentais, especiais, consequenciais ou punitivos decorrentes do uso do Serviço, mesmo que avisados da possibilidade de tais danos.",
      },
      {
        heading: "8. Modificações aos Termos",
        body: "Reservamo-nos o direito de modificar estes Termos a qualquer momento. O uso continuado do Serviço após as alterações constitui aceitação dos Termos atualizados. Notificaremos os utilizadores registados sobre alterações materiais por e-mail.",
      },
      {
        heading: "9. Lei Aplicável",
        body: "Estes Termos serão regidos e interpretados de acordo com a lei aplicável, sem consideração aos princípios de conflito de leis.",
      },
      {
        heading: "10. Contacto",
        body: "Dúvidas sobre estes Termos? Contacte-nos em legal@briteadvisor.com.",
      },
    ],
  },

  es: {
    title: "Términos de Servicio",
    updated: "Última actualización: 27 de abril de 2026",
    sections: [
      {
        heading: "1. Aceptación de los Términos",
        body: 'Al acceder o utilizar BRITE Advisor ("el Servicio"), acepta quedar vinculado por estos Términos de Servicio. Si no está de acuerdo con estos términos, no utilice el Servicio.',
      },
      {
        heading: "2. Descripción del Servicio",
        body: "BRITE Advisor es una herramienta de diagnóstico de arquitectura impulsada por IA, basada en el framework Business-Referenced Integration Technology Election (BRITE). Proporciona recomendaciones y análisis basados en las entradas del usuario y debe utilizarse como herramienta de apoyo a la decisión, no como sustituto del asesoramiento profesional arquitectónico o técnico.",
      },
      {
        heading: "3. Cuentas de Usuario",
        body: "Al crear una cuenta, usted es responsable de mantener la confidencialidad de sus credenciales y de toda la actividad en su cuenta. Acepta notificarnos de inmediato cualquier uso no autorizado de su cuenta.",
      },
      {
        heading: "4. Uso Aceptable",
        body: "Usted acepta no:",
        items: [
          "Utilizar el Servicio para cualquier propósito ilegal o en violación de normativas",
          "Intentar obtener acceso no autorizado a cualquier parte del Servicio",
          "Realizar ingeniería inversa, descompilar o desensamblar cualquier parte del Servicio",
          "Usar medios automatizados para acceder al Servicio sin nuestro permiso expreso por escrito",
          "Enviar información falsa o engañosa a través del Servicio",
        ],
      },
      {
        heading: "5. Propiedad Intelectual",
        body: "Todo el contenido, marca y tecnología del Servicio son propiedad exclusiva de BRITE Advisor y sus licenciantes. El nombre y la metodología del BRITE Framework son propiedad intelectual protegida. Nada en estos Términos le otorga derecho alguno a utilizar nuestras marcas registradas, logotipos u otra información propietaria.",
      },
      {
        heading: "6. Contenido Generado por IA",
        body: "Los diagnósticos y recomendaciones generados por nuestra IA se proporcionan únicamente con fines informativos. No ofrecemos garantías sobre la exactitud, integridad o idoneidad para un propósito particular del contenido generado por IA. Usted asume plena responsabilidad por las decisiones tomadas basándose en los resultados del Servicio.",
      },
      {
        heading: "7. Limitación de Responsabilidad",
        body: "En la máxima medida permitida por la ley, BRITE Advisor y sus afiliados no serán responsables de daños indirectos, incidentales, especiales, consecuentes o punitivos derivados del uso del Servicio, incluso si se les ha advertido de la posibilidad de dichos daños.",
      },
      {
        heading: "8. Modificaciones a los Términos",
        body: "Nos reservamos el derecho de modificar estos Términos en cualquier momento. El uso continuado del Servicio tras los cambios constituye la aceptación de los Términos actualizados. Notificaremos a los usuarios registrados sobre cambios materiales por correo electrónico.",
      },
      {
        heading: "9. Ley Aplicable",
        body: "Estos Términos se regirán e interpretarán de acuerdo con la ley aplicable, sin tener en cuenta los principios de conflicto de leyes.",
      },
      {
        heading: "10. Contacto",
        body: "¿Preguntas sobre estos Términos? Contáctenos en legal@briteadvisor.com.",
      },
    ],
  },

  fr: {
    title: "Conditions d'utilisation",
    updated: "Dernière mise à jour : 27 avril 2026",
    sections: [
      {
        heading: "1. Acceptation des conditions",
        body: "En accédant ou en utilisant BRITE Advisor (« le Service »), vous acceptez d'être lié par ces Conditions d'utilisation. Si vous n'acceptez pas ces conditions, n'utilisez pas le Service.",
      },
      {
        heading: "2. Description du Service",
        body: "BRITE Advisor est un outil de diagnostic d'architecture propulsé par l'IA, basé sur le framework Business-Referenced Integration Technology Election (BRITE). Il fournit des recommandations et des analyses basées sur les entrées des utilisateurs et doit être utilisé comme outil d'aide à la décision, et non comme substitut à des conseils professionnels en architecture ou en technique.",
      },
      {
        heading: "3. Comptes utilisateurs",
        body: "En créant un compte, vous êtes responsable de la confidentialité de vos identifiants et de toute activité effectuée depuis votre compte. Vous vous engagez à nous notifier immédiatement de toute utilisation non autorisée de votre compte.",
      },
      {
        heading: "4. Utilisation acceptable",
        body: "Vous vous engagez à ne pas :",
        items: [
          "Utiliser le Service à des fins illégales ou en violation de réglementations",
          "Tenter d'obtenir un accès non autorisé à toute partie du Service",
          "Procéder à de la rétro-ingénierie, décompiler ou désassembler toute partie du Service",
          "Utiliser des moyens automatisés pour accéder au Service sans notre autorisation écrite expresse",
          "Soumettre des informations fausses ou trompeuses via le Service",
        ],
      },
      {
        heading: "5. Propriété intellectuelle",
        body: "Tout le contenu, la marque et la technologie du Service sont la propriété exclusive de BRITE Advisor et de ses concédants. Le nom et la méthodologie du BRITE Framework sont des propriétés intellectuelles protégées. Rien dans ces Conditions ne vous accorde le droit d'utiliser nos marques, logos ou autres informations propriétaires.",
      },
      {
        heading: "6. Contenu généré par l'IA",
        body: "Les diagnostics et recommandations générés par notre IA sont fournis à titre informatif uniquement. Nous ne donnons aucune garantie quant à l'exactitude, l'exhaustivité ou l'adéquation à un usage particulier du contenu généré par l'IA. Vous assumez l'entière responsabilité des décisions prises sur la base des résultats du Service.",
      },
      {
        heading: "7. Limitation de responsabilité",
        body: "Dans toute la mesure permise par la loi, BRITE Advisor et ses affiliés ne sauraient être tenus responsables de dommages indirects, accessoires, spéciaux, consécutifs ou punitifs découlant de votre utilisation du Service, même s'ils ont été avertis de la possibilité de tels dommages.",
      },
      {
        heading: "8. Modifications des conditions",
        body: "Nous nous réservons le droit de modifier ces Conditions à tout moment. La poursuite de l'utilisation du Service après les modifications vaut acceptation des Conditions mises à jour. Nous informerons les utilisateurs inscrits des modifications importantes par e-mail.",
      },
      {
        heading: "9. Droit applicable",
        body: "Ces Conditions sont régies et interprétées conformément au droit applicable, sans égard aux principes de conflit de lois.",
      },
      {
        heading: "10. Contact",
        body: "Des questions sur ces Conditions ? Contactez-nous à legal@briteadvisor.com.",
      },
    ],
  },
};
